import{a as p,S as g,i as l}from"./assets/vendor-BezXTN6Z.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const y="56198114-ccacac48ed3b4e5ff26b93aa4",h="https://pixabay.com/api/";function b(i){return p.get(h,{params:{key:y,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data)}const f=document.querySelector(".gallery"),u=document.querySelector(".loader");let n=null;function L(i){const o=i.map(({webformatURL:r,largeImageURL:a,tags:e,likes:t,views:s,comments:d,downloads:m})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${r}" alt="${e}" loading="lazy" />
          <div class="card-info">
            <p class="card-info-item"><b>Likes</b><span>${t}</span></p>
            <p class="card-info-item"><b>Views</b><span>${s}</span></p>
            <p class="card-info-item"><b>Comments</b><span>${d}</span></p>
            <p class="card-info-item"><b>Downloads</b><span>${m}</span></p>
          </div>
        </a>
      </li>`).join("");f.insertAdjacentHTML("beforeend",o),n?n.refresh():n=new g(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function C(){f.innerHTML=""}function v(){u.classList.remove("hidden")}function E(){u.classList.add("hidden")}const c=document.querySelector(".form");c.addEventListener("submit",i=>{i.preventDefault();const o=c.elements["search-text"].value.trim();o&&(C(),v(),b(o).then(r=>{if(r.hits.length===0){l.show({icon:"ico-error",iconColor:"#fff",title:"Error",titleColor:"#fff",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",timeout:5e3});return}L(r.hits)}).catch(r=>{l.show({icon:"ico-error",iconColor:"#fff",title:"Error",titleColor:"#fff",message:r.message,messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",timeout:5e3})}).finally(()=>{E()}))});
//# sourceMappingURL=index.js.map
